name: kg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  fl_chart: ^1.1.0
  sqflite: ^2.4.2
  provider: ^6.1.5
  connectivity_plus: ^7.0.0
  cloud_firestore: ^6.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.2
  shared_preferences: ^2.2.3
  workmanager: ^0.9.0
  printing: ^5.14.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.png
